import { MedicineRequest } from '../types/medicineRequest';

export const mockMedicineRequests: MedicineRequest[] = [
  {
    id: 'req-001',
    medicineName: 'Dolo 650',
    imageAttached: false,
    customerName: 'Rahul Patel',
    customerPhone: '+91 98765 43210',
    pharmacyName: 'ABC Medical Store',
    requestedAt: new Date(new Date().setHours(new Date().getHours() - 1)).toISOString(),
    status: 'WAITING',
    customerConfirmation: 'PENDING',
  },
  {
    id: 'req-002',
    medicineName: 'Azithromycin 500',
    imageAttached: true,
    customerName: 'Priya Shah',
    customerPhone: '+91 91234 56789',
    pharmacyName: 'ABC Medical Store',
    requestedAt: new Date(new Date().setHours(new Date().getHours() - 2)).toISOString(),
    status: 'AVAILABLE',
    responseMessage: 'Medicine marked as available.',
    customerConfirmation: 'PENDING',
  },
  {
    id: 'req-003',
    medicineName: 'Crocin Advance',
    imageAttached: false,
    customerName: 'Amit Patel',
    customerPhone: '+91 99887 76655',
    pharmacyName: 'ABC Medical Store',
    requestedAt: new Date(new Date().setHours(new Date().getHours() - 3)).toISOString(),
    status: 'CAN_ARRANGE',
    responseMessage: 'Can arrange within 2 hours.',
    customerConfirmation: 'PENDING',
  },
  {
    id: 'req-004',
    medicineName: undefined,
    imageAttached: true,
    customerName: 'Neha Desai',
    customerPhone: '+91 98765 11111',
    pharmacyName: 'ABC Medical Store',
    requestedAt: new Date(new Date().setHours(new Date().getHours() - 5)).toISOString(),
    status: 'NOT_AVAILABLE',
    responseMessage: 'Currently unavailable.',
    customerConfirmation: 'PENDING',
  },
  {
    id: 'req-005',
    medicineName: 'Paracetamol 500mg',
    imageAttached: true,
    customerName: 'Sanjay Kumar',
    customerPhone: '+91 99999 88888',
    pharmacyName: 'ABC Medical Store',
    requestedAt: new Date(new Date().setHours(new Date().getHours() - 6)).toISOString(),
    status: 'WAITING',
    customerConfirmation: 'PENDING',
  },
  {
    id: 'req-006',
    medicineName: 'Thyroxine 50mcg',
    imageAttached: false,
    customerName: 'Meera Reddy',
    customerPhone: '+91 97777 66666',
    pharmacyName: 'ABC Medical Store',
    requestedAt: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
    status: 'AVAILABLE',
    customerConfirmation: 'PENDING',
  },
  {
    id: 'req-007',
    medicineName: undefined,
    imageAttached: true,
    customerName: 'Vikram Singh',
    customerPhone: '+91 94444 33333',
    pharmacyName: 'ABC Medical Store',
    requestedAt: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
    status: 'WAITING',
    customerConfirmation: 'PENDING',
  },
  {
    id: 'req-008',
    medicineName: 'Pan D Capsule',
    imageAttached: false,
    customerName: 'Anjali Sharma',
    customerPhone: '+91 92222 11111',
    pharmacyName: 'ABC Medical Store',
    requestedAt: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
    status: 'CAN_ARRANGE',
    responseMessage: 'Stock arriving tomorrow morning.',
    customerConfirmation: 'PENDING',
  },
];
