ALTER TABLE pharmacies
ADD COLUMN IF NOT EXISTS plan_type VARCHAR(50) DEFAULT 'FREE_TRIAL',
ADD COLUMN IF NOT EXISTS trial_start_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS subscription_end_date TIMESTAMP WITH TIME ZONE;
