ALTER TABLE pharmacies ADD COLUMN IF NOT EXISTS email VARCHAR(255);
ALTER TABLE pharmacies ADD COLUMN IF NOT EXISTS reg_no VARCHAR(255);
ALTER TABLE pharmacies ADD COLUMN IF NOT EXISTS gstin VARCHAR(50);
