-- Phase 1 & 2: Pharmacy and Medicines GST Fields
ALTER TABLE pharmacies 
ADD COLUMN IF NOT EXISTS gst_registered BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS gstin VARCHAR(15),
ADD COLUMN IF NOT EXISTS state VARCHAR(100);

ALTER TABLE medicines 
ADD COLUMN IF NOT EXISTS hsn_code VARCHAR(20),
ADD COLUMN IF NOT EXISTS gst_rate NUMERIC(5,2) DEFAULT 0;

-- Phase 3 & 4: Bill and Bill Items GST Snapshot
ALTER TABLE bills
ADD COLUMN IF NOT EXISTS total_taxable_amount NUMERIC(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_cgst NUMERIC(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_sgst NUMERIC(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_igst NUMERIC(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_gst NUMERIC(10,2) DEFAULT 0;

ALTER TABLE bill_items
ADD COLUMN IF NOT EXISTS hsn_code VARCHAR(20),
ADD COLUMN IF NOT EXISTS gst_rate NUMERIC(5,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS taxable_amount NUMERIC(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS cgst NUMERIC(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS sgst NUMERIC(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS igst NUMERIC(10,2) DEFAULT 0;
